/**
 * Central catalogue of @icon-park/react icons used across the app in place
 * of raw emoji. Every icon here is rendered with the "multi-color" theme so
 * the app keeps the same playful, colorful feel emoji used to provide.
 *
 * Each entry's `key` is icon-park's own kebab-case icon name. It is also
 * the exact string persisted as `Party.emoji` / `Expense.emoji` — the
 * field name stayed the same to avoid a Google Sheets schema change, only
 * the kind of string it stores changed (see CLAUDE.md's "Google Sheets
 * schema" section). This is a breaking change for any party/expense saved
 * before this feature; there is no legacy-emoji fallback by design.
 */
import type { ComponentType } from "react";
import {
  Acceleration,
  Airplane,
  AirplaneWindow,
  AirplaneWindowOne,
  AnchorTwo,
  AppleOne,
  Archery,
  Aviation,
  Avocado,
  AvocadoOne,
  Badminton,
  BaggageDelay,
  Banana,
  Barbecue,
  Baseball,
  Basketball,
  BeachUmbrella,
  Beer,
  BeerMug,
  BirthdayCake,
  Bone,
  BottleOne,
  BottleThree,
  BottleTwo,
  Bowl,
  BowlOne,
  Bowling,
  Boxing,
  BrakePads,
  Bread,
  BreadMachine,
  BreadOne,
  BusOne,
  BusTwo,
  CableCar,
  Cake,
  CakeFive,
  CakeFour,
  CakeOne,
  CakeThree,
  CakeTwo,
  Camp,
  Candy,
  CannedFruit,
  CarBattery,
  Carrot,
  ChafingDish,
  ChafingDishOne,
  CheckIn,
  Cheese,
  ChefHatOne,
  Cherry,
  Chess,
  Chicken,
  ChickenLeg,
  Chili,
  ChoppingBoard,
  ChopsticksFork,
  Circus,
  Cocktail,
  CoconutTree,
  Cola,
  CompassOne,
  Consignment,
  Cook,
  Cooking,
  Crab,
  Croissant,
  Cruise,
  CupFour,
  CupOne,
  Descend,
  Diving,
  Doughnut,
  Drink,
  Drumstick,
  Dumbbell,
  Earth,
  Egg,
  EggOne,
  Eggplant,
  Enquire,
  FerrisWheel,
  Fireworks,
  Fish,
  Fishing,
  Fitness,
  Flag,
  FlightAirflow,
  FlightSafety,
  Football,
  ForkSpoon,
  FrenchFries,
  Frigate,
  Game,
  GameConsole,
  Gamepad,
  Garlic,
  GateMachine,
  Globe,
  Glove,
  Goblet,
  GobletCracking,
  GobletFull,
  GobletOne,
  GoldMedal,
  GolfCourse,
  Gps,
  GuideBoard,
  Gymnastics,
  Hamburger,
  HamburgerOne,
  HighSpeedRail,
  Hockey,
  Homestay,
  Honey,
  HoneyOne,
  HotAirBalloon,
  HotPot,
  HotPotOne,
  Hotel,
  Icecream,
  IcecreamFive,
  IcecreamFour,
  IcecreamOne,
  IcecreamThree,
  IcecreamTwo,
  InFlight,
  International,
  Journey,
  Juice,
  KettleOne,
  KitchenKnife,
  KnifeFork,
  Landing,
  Landscape,
  Lemon,
  Liqueur,
  Local,
  LocalPin,
  LocalTwo,
  Lollipop,
  Luggage,
  MacadamiaNut,
  ManualGear,
  MapDistance,
  MapDraw,
  MapRoad,
  MapRoadTwo,
  MapTwo,
  Mark,
  MeasuringCup,
  Microphone,
  Milk,
  MilkOne,
  Mountain,
  Mounted,
  Movie,
  MovieBoard,
  MuseumOne,
  Music,
  Navigation,
  Noodles,
  Nut,
  Orange,
  OrangeOne,
  Oven,
  OvenTray,
  PaintedEggshell,
  Parachute,
  Parking,
  PartyBalloon,
  PassportOne,
  Peach,
  Pear,
  Peas,
  Pennant,
  Photograph,
  Pineapple,
  Planet,
  Popcorn,
  PopcornOne,
  Pot,
  Pumpkin,
  PyramidOne,
  Radish,
  RadishOne,
  Railway,
  Refrigerator,
  Repositioning,
  Resting,
  Rice,
  Riding,
  RidingOne,
  Road,
  RoadCone,
  RoadOne,
  RoadSign,
  RoadSignBoth,
  Rocket,
  RoundTrip,
  Rowing,
  Rugby,
  SailboatOne,
  Sailing,
  Sandals,
  Sandwich,
  SandwichOne,
  Scallion,
  Selfie,
  SetOff,
  Shade,
  Ship,
  Shovel,
  ShovelOne,
  Shrimp,
  Skate,
  Skating,
  SkiingNordic,
  Snacks,
  Soccer,
  SoybeanMilkMaker,
  Spoon,
  Sport,
  SteeringWheel,
  Sunbath,
  Sunrise,
  Sunset,
  Sunshade,
  SwimmingPool,
  Tabletennis,
  TakeOff,
  TakeOffOne,
  Taxi,
  Tea,
  TeaDrink,
  Teapot,
  Tennis,
  Tent,
  TentBanner,
  Theater,
  ThermosCup,
  TicketsChecked,
  TicketsOne,
  TicketsTwo,
  Tomato,
  TourBus,
  Train,
  Transfer,
  Transport,
  Tray,
  Treadmill,
  Turkey,
  Universal,
  Vacation,
  VegetableBasket,
  Vegetables,
  ViciaFaba,
  Volleyball,
  VrGlasses,
  Watermelon,
  WatermelonOne,
  Weightlifting,
  Wheelchair,
  World,
} from "@icon-park/react";
import { DEFAULT_EXPENSE_ICON_KEY, DEFAULT_PARTY_ICON_KEY } from "@/domain/icons";

export { DEFAULT_EXPENSE_ICON_KEY, DEFAULT_PARTY_ICON_KEY };

/** Minimal prop surface shared by every icon-park icon component. */
export interface IconParkIconProps {
  theme?: "outline" | "filled" | "two-tone" | "multi-color";
  size?: string | number;
  className?: string;
}

export type IconParkIcon = ComponentType<IconParkIconProps>;

export interface IconOption {
  key: string;
  label: string;
  Icon: IconParkIcon;
}

export const FOOD_ICONS: IconOption[] = [
  { key: "apple-one", label: "Maçã", Icon: AppleOne },
  { key: "avocado", label: "Abacate", Icon: Avocado },
  { key: "avocado-one", label: "Abacate", Icon: AvocadoOne },
  { key: "banana", label: "Banana", Icon: Banana },
  { key: "barbecue", label: "Churrasco", Icon: Barbecue },
  { key: "beer", label: "Cerveja", Icon: Beer },
  { key: "beer-mug", label: "Caneca de cerveja", Icon: BeerMug },
  { key: "birthday-cake", label: "Bolo de aniversário", Icon: BirthdayCake },
  { key: "bone", label: "Osso", Icon: Bone },
  { key: "bottle-one", label: "Garrafa", Icon: BottleOne },
  { key: "bottle-three", label: "Garrafa", Icon: BottleThree },
  { key: "bottle-two", label: "Garrafa", Icon: BottleTwo },
  { key: "bowl", label: "Tigela de macarrão", Icon: Bowl },
  { key: "bowl-one", label: "Tigela", Icon: BowlOne },
  { key: "bread", label: "Pão", Icon: Bread },
  { key: "bread-machine", label: "Máquina de pão", Icon: BreadMachine },
  { key: "bread-one", label: "Pão", Icon: BreadOne },
  { key: "cake", label: "Bolo", Icon: Cake },
  { key: "cake-five", label: "Bolo", Icon: CakeFive },
  { key: "cake-four", label: "Bolo", Icon: CakeFour },
  { key: "cake-one", label: "Bolo", Icon: CakeOne },
  { key: "cake-three", label: "Bolo", Icon: CakeThree },
  { key: "cake-two", label: "Bolo", Icon: CakeTwo },
  { key: "candy", label: "Doce", Icon: Candy },
  { key: "canned-fruit", label: "Fruta em lata", Icon: CannedFruit },
  { key: "carrot", label: "Cenoura", Icon: Carrot },
  { key: "chafing-dish", label: "Fondue", Icon: ChafingDish },
  { key: "chafing-dish-one", label: "Fondue", Icon: ChafingDishOne },
  { key: "cheese", label: "Queijo", Icon: Cheese },
  { key: "chef-hat-one", label: "Chapéu de chef", Icon: ChefHatOne },
  { key: "cherry", label: "Cereja", Icon: Cherry },
  { key: "chicken", label: "Frango", Icon: Chicken },
  { key: "chicken-leg", label: "Coxa de frango", Icon: ChickenLeg },
  { key: "chili", label: "Pimenta", Icon: Chili },
  { key: "chopping-board", label: "Tábua de corte", Icon: ChoppingBoard },
  { key: "chopsticks-fork", label: "Hashi e garfo", Icon: ChopsticksFork },
  { key: "cola", label: "Refrigerante", Icon: Cola },
  { key: "cook", label: "Cozinhar", Icon: Cook },
  { key: "cooking", label: "Cozinhando", Icon: Cooking },
  { key: "crab", label: "Caranguejo", Icon: Crab },
  { key: "croissant", label: "Croissant", Icon: Croissant },
  { key: "cup-four", label: "Xícara", Icon: CupFour },
  { key: "cup-one", label: "Copo", Icon: CupOne },
  { key: "doughnut", label: "Rosquinha", Icon: Doughnut },
  { key: "drink", label: "Bebida", Icon: Drink },
  { key: "drumstick", label: "Coxinha da asa", Icon: Drumstick },
  { key: "egg", label: "Ovo frito", Icon: Egg },
  { key: "egg-one", label: "Ovo", Icon: EggOne },
  { key: "eggplant", label: "Berinjela", Icon: Eggplant },
  { key: "fish", label: "Peixe", Icon: Fish },
  { key: "fork-spoon", label: "Garfo e colher", Icon: ForkSpoon },
  { key: "french-fries", label: "Batata frita", Icon: FrenchFries },
  { key: "garlic", label: "Alho", Icon: Garlic },
  { key: "glove", label: "Luva de cozinha", Icon: Glove },
  { key: "goblet", label: "Taça", Icon: Goblet },
  { key: "goblet-cracking", label: "Taça quebrando", Icon: GobletCracking },
  { key: "goblet-full", label: "Taça cheia", Icon: GobletFull },
  { key: "goblet-one", label: "Taça", Icon: GobletOne },
  { key: "hamburger", label: "Hambúrguer", Icon: Hamburger },
  { key: "hamburger-one", label: "Hambúrguer", Icon: HamburgerOne },
  { key: "honey", label: "Mel", Icon: Honey },
  { key: "honey-one", label: "Mel", Icon: HoneyOne },
  { key: "hot-pot", label: "Fondue chinês", Icon: HotPot },
  { key: "hot-pot-one", label: "Fondue chinês", Icon: HotPotOne },
  { key: "icecream", label: "Sorvete", Icon: Icecream },
  { key: "icecream-five", label: "Picolé", Icon: IcecreamFive },
  { key: "icecream-four", label: "Sorvete", Icon: IcecreamFour },
  { key: "icecream-one", label: "Sorvete", Icon: IcecreamOne },
  { key: "icecream-three", label: "Picolé", Icon: IcecreamThree },
  { key: "icecream-two", label: "Sorvete", Icon: IcecreamTwo },
  { key: "juice", label: "Suco", Icon: Juice },
  { key: "kettle-one", label: "Chaleira", Icon: KettleOne },
  { key: "kitchen-knife", label: "Faca de cozinha", Icon: KitchenKnife },
  { key: "knife-fork", label: "Faca e garfo", Icon: KnifeFork },
  { key: "lemon", label: "Limão", Icon: Lemon },
  { key: "liqueur", label: "Coquetel", Icon: Liqueur },
  { key: "lollipop", label: "Pirulito", Icon: Lollipop },
  { key: "macadamia-nut", label: "Castanha", Icon: MacadamiaNut },
  { key: "measuring-cup", label: "Copo medidor", Icon: MeasuringCup },
  { key: "milk", label: "Leite", Icon: Milk },
  { key: "milk-one", label: "Leite", Icon: MilkOne },
  { key: "noodles", label: "Macarrão", Icon: Noodles },
  { key: "nut", label: "Nozes", Icon: Nut },
  { key: "orange", label: "Laranja", Icon: Orange },
  { key: "orange-one", label: "Rodela de limão", Icon: OrangeOne },
  { key: "oven", label: "Forno", Icon: Oven },
  { key: "oven-tray", label: "Assadeira", Icon: OvenTray },
  { key: "painted-eggshell", label: "Ovo decorado", Icon: PaintedEggshell },
  { key: "peach", label: "Pêssego", Icon: Peach },
  { key: "pear", label: "Pera", Icon: Pear },
  { key: "peas", label: "Ervilhas", Icon: Peas },
  { key: "pineapple", label: "Abacaxi", Icon: Pineapple },
  { key: "popcorn", label: "Pipoca", Icon: Popcorn },
  { key: "popcorn-one", label: "Pipoca", Icon: PopcornOne },
  { key: "pot", label: "Panela", Icon: Pot },
  { key: "pumpkin", label: "Abóbora", Icon: Pumpkin },
  { key: "radish", label: "Rabanete", Icon: Radish },
  { key: "radish-one", label: "Rabanete", Icon: RadishOne },
  { key: "refrigerator", label: "Geladeira", Icon: Refrigerator },
  { key: "rice", label: "Arroz", Icon: Rice },
  { key: "sandwich", label: "Sanduíche", Icon: Sandwich },
  { key: "sandwich-one", label: "Sanduíche", Icon: SandwichOne },
  { key: "scallion", label: "Cebolinha", Icon: Scallion },
  { key: "shovel", label: "Espátula", Icon: Shovel },
  { key: "shovel-one", label: "Espátula", Icon: ShovelOne },
  { key: "shrimp", label: "Camarão", Icon: Shrimp },
  { key: "snacks", label: "Petiscos", Icon: Snacks },
  { key: "soybean-milk-maker", label: "Máquina de leite de soja", Icon: SoybeanMilkMaker },
  { key: "spoon", label: "Colher", Icon: Spoon },
  { key: "tea", label: "Chá", Icon: Tea },
  { key: "tea-drink", label: "Chá gelado", Icon: TeaDrink },
  { key: "teapot", label: "Bule", Icon: Teapot },
  { key: "thermos-cup", label: "Garrafa térmica", Icon: ThermosCup },
  { key: "tomato", label: "Tomate", Icon: Tomato },
  { key: "tray", label: "Bandeja", Icon: Tray },
  { key: "turkey", label: "Peru", Icon: Turkey },
  { key: "vegetable-basket", label: "Cesta de vegetais", Icon: VegetableBasket },
  { key: "vegetables", label: "Vegetais", Icon: Vegetables },
  { key: "vicia-faba", label: "Fava", Icon: ViciaFaba },
  { key: "watermelon", label: "Melancia", Icon: Watermelon },
  { key: "watermelon-one", label: "Melancia", Icon: WatermelonOne },
];

export const SPORT_ICONS: IconOption[] = [
  { key: "archery", label: "Arco e flecha", Icon: Archery },
  { key: "badminton", label: "Badminton", Icon: Badminton },
  { key: "baseball", label: "Beisebol", Icon: Baseball },
  { key: "basketball", label: "Basquete", Icon: Basketball },
  { key: "bowling", label: "Boliche", Icon: Bowling },
  { key: "boxing", label: "Boxe", Icon: Boxing },
  { key: "chess", label: "Xadrez", Icon: Chess },
  { key: "dumbbell", label: "Halteres", Icon: Dumbbell },
  { key: "fitness", label: "Academia", Icon: Fitness },
  { key: "football", label: "Futebol americano", Icon: Football },
  { key: "gold-medal", label: "Medalha de ouro", Icon: GoldMedal },
  { key: "golf-course", label: "Golfe", Icon: GolfCourse },
  { key: "gymnastics", label: "Ginástica", Icon: Gymnastics },
  { key: "hockey", label: "Hóquei", Icon: Hockey },
  { key: "riding", label: "Equitação", Icon: Riding },
  { key: "rowing", label: "Remo", Icon: Rowing },
  { key: "rugby", label: "Rúgbi", Icon: Rugby },
  { key: "skate", label: "Skate", Icon: Skate },
  { key: "skating", label: "Patinação", Icon: Skating },
  { key: "skiing-nordic", label: "Esqui", Icon: SkiingNordic },
  { key: "soccer", label: "Futebol", Icon: Soccer },
  { key: "sport", label: "Esporte", Icon: Sport },
  { key: "swimming-pool", label: "Piscina", Icon: SwimmingPool },
  { key: "tabletennis", label: "Tênis de mesa", Icon: Tabletennis },
  { key: "tennis", label: "Tênis", Icon: Tennis },
  { key: "treadmill", label: "Esteira", Icon: Treadmill },
  { key: "volleyball", label: "Vôlei", Icon: Volleyball },
  { key: "weightlifting", label: "Levantamento de peso", Icon: Weightlifting },
];

export const ACTIVITY_ICONS: IconOption[] = [
  { key: "acceleration", label: "Aceleração", Icon: Acceleration },
  { key: "airplane", label: "Avião", Icon: Airplane },
  { key: "airplane-window", label: "Janela do avião", Icon: AirplaneWindow },
  { key: "airplane-window-one", label: "Janela do avião", Icon: AirplaneWindowOne },
  { key: "anchor-two", label: "Âncora", Icon: AnchorTwo },
  { key: "aviation", label: "Aviação", Icon: Aviation },
  { key: "baggage-delay", label: "Bagagem atrasada", Icon: BaggageDelay },
  { key: "brake-pads", label: "Pastilha de freio", Icon: BrakePads },
  { key: "bus-one", label: "Ônibus", Icon: BusOne },
  { key: "bus-two", label: "Ônibus", Icon: BusTwo },
  { key: "cable-car", label: "Teleférico", Icon: CableCar },
  { key: "camp", label: "Acampamento", Icon: Camp },
  { key: "car-battery", label: "Bateria do carro", Icon: CarBattery },
  { key: "check-in", label: "Check-in", Icon: CheckIn },
  { key: "cocktail", label: "Coquetel", Icon: Cocktail },
  { key: "coconut-tree", label: "Coqueiro", Icon: CoconutTree },
  { key: "compass-one", label: "Bússola", Icon: CompassOne },
  { key: "consignment", label: "Despacho de bagagem", Icon: Consignment },
  { key: "cruise", label: "Cruzeiro", Icon: Cruise },
  { key: "descend", label: "Descida", Icon: Descend },
  { key: "diving", label: "Mergulho", Icon: Diving },
  { key: "earth", label: "Terra", Icon: Earth },
  { key: "enquire", label: "Inspeção de segurança", Icon: Enquire },
  { key: "fishing", label: "Pesca", Icon: Fishing },
  { key: "flag", label: "Bandeira", Icon: Flag },
  { key: "flight-airflow", label: "Turbulência", Icon: FlightAirflow },
  { key: "flight-safety", label: "Segurança de voo", Icon: FlightSafety },
  { key: "frigate", label: "Fragata", Icon: Frigate },
  { key: "gate-machine", label: "Catraca de embarque", Icon: GateMachine },
  { key: "globe", label: "Globo", Icon: Globe },
  { key: "gps", label: "GPS", Icon: Gps },
  { key: "guide-board", label: "Placa de sinalização", Icon: GuideBoard },
  { key: "high-speed-rail", label: "Trem-bala", Icon: HighSpeedRail },
  { key: "homestay", label: "Pousada", Icon: Homestay },
  { key: "hot-air-balloon", label: "Balão de ar quente", Icon: HotAirBalloon },
  { key: "in-flight", label: "Em voo", Icon: InFlight },
  { key: "international", label: "Internacional", Icon: International },
  { key: "journey", label: "Viagem", Icon: Journey },
  { key: "landing", label: "Pouso", Icon: Landing },
  { key: "landscape", label: "Paisagem", Icon: Landscape },
  { key: "local", label: "Localização confirmada", Icon: Local },
  { key: "local-pin", label: "Local", Icon: LocalPin },
  { key: "local-two", label: "Local", Icon: LocalTwo },
  { key: "luggage", label: "Mala", Icon: Luggage },
  { key: "manual-gear", label: "Câmbio manual", Icon: ManualGear },
  { key: "map-distance", label: "Distância no mapa", Icon: MapDistance },
  { key: "map-draw", label: "Traçar rota", Icon: MapDraw },
  { key: "map-road", label: "Mapa e rota", Icon: MapRoad },
  { key: "map-road-two", label: "Mapa e rota", Icon: MapRoadTwo },
  { key: "map-two", label: "Mapa", Icon: MapTwo },
  { key: "mark", label: "Marcador", Icon: Mark },
  { key: "mountain", label: "Montanha", Icon: Mountain },
  { key: "mounted", label: "Passeio a cavalo", Icon: Mounted },
  { key: "navigation", label: "Navegação", Icon: Navigation },
  { key: "parachute", label: "Paraquedas", Icon: Parachute },
  { key: "parking", label: "Estacionamento", Icon: Parking },
  { key: "passport-one", label: "Passaporte", Icon: PassportOne },
  { key: "pennant", label: "Bandeirola", Icon: Pennant },
  { key: "photograph", label: "Foto de viagem", Icon: Photograph },
  { key: "planet", label: "Planeta", Icon: Planet },
  { key: "pyramid-one", label: "Pirâmide", Icon: PyramidOne },
  { key: "railway", label: "Ferrovia", Icon: Railway },
  { key: "repositioning", label: "Reposicionar", Icon: Repositioning },
  { key: "resting", label: "Descanso", Icon: Resting },
  { key: "riding-one", label: "Passeio a cavalo", Icon: RidingOne },
  { key: "road", label: "Estrada", Icon: Road },
  { key: "road-cone", label: "Cone de trânsito", Icon: RoadCone },
  { key: "road-one", label: "Estrada", Icon: RoadOne },
  { key: "road-sign", label: "Placa de trânsito", Icon: RoadSign },
  { key: "road-sign-both", label: "Placa de trânsito", Icon: RoadSignBoth },
  { key: "rocket", label: "Foguete", Icon: Rocket },
  { key: "round-trip", label: "Ida e volta", Icon: RoundTrip },
  { key: "sailboat-one", label: "Veleiro", Icon: SailboatOne },
  { key: "sailing", label: "Navegação a vela", Icon: Sailing },
  { key: "sandals", label: "Sandálias", Icon: Sandals },
  { key: "selfie", label: "Selfie", Icon: Selfie },
  { key: "set-off", label: "Partida", Icon: SetOff },
  { key: "shade", label: "Sombra", Icon: Shade },
  { key: "ship", label: "Navio", Icon: Ship },
  { key: "steering-wheel", label: "Volante", Icon: SteeringWheel },
  { key: "sunbath", label: "Banho de sol", Icon: Sunbath },
  { key: "sunrise", label: "Nascer do sol", Icon: Sunrise },
  { key: "sunset", label: "Pôr do sol", Icon: Sunset },
  { key: "sunshade", label: "Guarda-sol", Icon: Sunshade },
  { key: "take-off", label: "Decolagem", Icon: TakeOff },
  { key: "take-off-one", label: "Decolagem", Icon: TakeOffOne },
  { key: "taxi", label: "Táxi", Icon: Taxi },
  { key: "tent", label: "Barraca", Icon: Tent },
  { key: "tent-banner", label: "Barraca com bandeira", Icon: TentBanner },
  { key: "theater", label: "Cinema", Icon: Theater },
  { key: "tickets-checked", label: "Ingresso validado", Icon: TicketsChecked },
  { key: "tickets-one", label: "Ingresso", Icon: TicketsOne },
  { key: "tickets-two", label: "Ingresso", Icon: TicketsTwo },
  { key: "tour-bus", label: "Ônibus de turismo", Icon: TourBus },
  { key: "train", label: "Trem", Icon: Train },
  { key: "transfer", label: "Conexão de voo", Icon: Transfer },
  { key: "transport", label: "Transporte", Icon: Transport },
  { key: "universal", label: "Universo", Icon: Universal },
  { key: "vacation", label: "Férias", Icon: Vacation },
  { key: "wheelchair", label: "Cadeira de rodas", Icon: Wheelchair },
  { key: "world", label: "Mundo", Icon: World },
  { key: "movie", label: "Filme", Icon: Movie },
  { key: "movie-board", label: "Claquete de cinema", Icon: MovieBoard },
  { key: "music", label: "Música", Icon: Music },
  { key: "microphone", label: "Show ao vivo", Icon: Microphone },
  { key: "party-balloon", label: "Balão de festa", Icon: PartyBalloon },
  { key: "fireworks", label: "Fogos de artifício", Icon: Fireworks },
  { key: "ferris-wheel", label: "Roda-gigante", Icon: FerrisWheel },
  { key: "circus", label: "Circo", Icon: Circus },
  { key: "museum-one", label: "Museu", Icon: MuseumOne },
  { key: "hotel", label: "Hotel", Icon: Hotel },
  { key: "beach-umbrella", label: "Guarda-sol de praia", Icon: BeachUmbrella },
  { key: "game", label: "Jogo", Icon: Game },
  { key: "game-console", label: "Videogame", Icon: GameConsole },
  { key: "gamepad", label: "Controle de videogame", Icon: Gamepad },
  { key: "vr-glasses", label: "Óculos de VR", Icon: VrGlasses },
];

export interface IconCategory {
  label: string;
  icons: IconOption[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  { label: "Comida & Bebida", icons: FOOD_ICONS },
  { label: "Esporte", icons: SPORT_ICONS },
  { label: "Atividades", icons: ACTIVITY_ICONS },
];

const ICON_MAP = new Map<string, IconOption>(
  ICON_CATEGORIES.flatMap((category) => category.icons).map((icon) => [icon.key, icon]),
);

/**
 * Resolves a stored `emoji` string to an icon-park component. Unknown
 * values (e.g. a raw emoji left over from before this feature) fall back
 * to the default expense icon instead of rendering as text.
 */
export function resolveIcon(key: string): IconParkIcon {
  return (ICON_MAP.get(key) ?? ICON_MAP.get(DEFAULT_EXPENSE_ICON_KEY)!).Icon;
}
