/**
 * Central catalogue of @icon-park/react icons used across the app in place
 * of raw emoji. Every icon here is rendered with the "multi-color" theme so
 * the app keeps the same playful, colorful feel emoji used to provide.
 *
 * Each entry's `key` is icon-park's own kebab-case icon name. It is also
 * the exact string persisted as `Party.emoji` / `Expense.emoji` — the
 * field name stayed the same to avoid a Google Sheets schema change, only
 * the kind of string it stores changed (see CLAUDE.md's "Google Sheets
 * schema" section). This is a breaking change for any party/expense saved
 * before this feature; there is no legacy-emoji fallback by design.
 *
 * `@icon-park/react`'s "multi-color" theme does **not** vary its own
 * colors per icon — every icon defaults to the exact same palette
 * (`#333`/`#2F88FF`/`#FFF`/`#43CCF8`) unless a `fill` array is supplied,
 * so out of the box the whole grid looked like one flat blue tint. Each
 * `IconOption` below carries a `fill` — one of the `PALETTE` tuples,
 * chosen per icon's subject (a banana is yellow, a tomato is red, ...) —
 * so icons read as individual colorful "stickers" instead of a uniform
 * blue set. `AppIcon` is the only place that actually applies it; always
 * render icons through it rather than pulling `Icon`/`fill` apart.
 */
import type { ComponentType } from "react";
import {
  Acceleration,
  Airplane,
  AirplaneWindow,
  AirplaneWindowOne,
  AnchorTwo,
  AppleOne,
  Archery,
  Aviation,
  Avocado,
  AvocadoOne,
  Badminton,
  BaggageDelay,
  Banana,
  Barbecue,
  Baseball,
  Basketball,
  BeachUmbrella,
  Beer,
  BeerMug,
  BirthdayCake,
  Bone,
  BottleOne,
  BottleThree,
  BottleTwo,
  Bowl,
  BowlOne,
  Bowling,
  Boxing,
  BrakePads,
  Bread,
  BreadMachine,
  BreadOne,
  BusOne,
  BusTwo,
  CableCar,
  Cake,
  CakeFive,
  CakeFour,
  CakeOne,
  CakeThree,
  CakeTwo,
  Camp,
  Candy,
  CannedFruit,
  CarBattery,
  Carrot,
  ChafingDish,
  ChafingDishOne,
  CheckIn,
  Cheese,
  ChefHatOne,
  Cherry,
  Chess,
  Chicken,
  ChickenLeg,
  Chili,
  ChoppingBoard,
  ChopsticksFork,
  Circus,
  Cocktail,
  CoconutTree,
  Cola,
  CompassOne,
  Consignment,
  Cook,
  Cooking,
  Crab,
  Croissant,
  Cruise,
  CupFour,
  CupOne,
  Descend,
  Diving,
  Doughnut,
  Drink,
  Drumstick,
  Dumbbell,
  Earth,
  Egg,
  EggOne,
  Eggplant,
  Enquire,
  FerrisWheel,
  Fireworks,
  Fish,
  Fishing,
  Fitness,
  Flag,
  FlightAirflow,
  FlightSafety,
  Football,
  ForkSpoon,
  FrenchFries,
  Frigate,
  Game,
  GameConsole,
  Gamepad,
  Garlic,
  GateMachine,
  Globe,
  Glove,
  Goblet,
  GobletCracking,
  GobletFull,
  GobletOne,
  GoldMedal,
  GolfCourse,
  Gps,
  GuideBoard,
  Gymnastics,
  Hamburger,
  HamburgerOne,
  HighSpeedRail,
  Hockey,
  Homestay,
  Honey,
  HoneyOne,
  HotAirBalloon,
  HotPot,
  HotPotOne,
  Hotel,
  Icecream,
  IcecreamFive,
  IcecreamFour,
  IcecreamOne,
  IcecreamThree,
  IcecreamTwo,
  InFlight,
  International,
  Journey,
  Juice,
  KettleOne,
  KitchenKnife,
  KnifeFork,
  Landing,
  Landscape,
  Lemon,
  Liqueur,
  Local,
  LocalPin,
  LocalTwo,
  Lollipop,
  Luggage,
  MacadamiaNut,
  ManualGear,
  MapDistance,
  MapDraw,
  MapRoad,
  MapRoadTwo,
  MapTwo,
  Mark,
  MeasuringCup,
  Microphone,
  Milk,
  MilkOne,
  Mountain,
  Mounted,
  Movie,
  MovieBoard,
  MuseumOne,
  Music,
  Navigation,
  Noodles,
  Nut,
  Orange,
  OrangeOne,
  Oven,
  OvenTray,
  PaintedEggshell,
  Parachute,
  Parking,
  PartyBalloon,
  PassportOne,
  Peach,
  Pear,
  Peas,
  Pennant,
  Photograph,
  Pineapple,
  Planet,
  Popcorn,
  PopcornOne,
  Pot,
  Pumpkin,
  PyramidOne,
  Radish,
  RadishOne,
  Railway,
  Refrigerator,
  Repositioning,
  Resting,
  Rice,
  Riding,
  RidingOne,
  Road,
  RoadCone,
  RoadOne,
  RoadSign,
  RoadSignBoth,
  Rocket,
  RoundTrip,
  Rowing,
  Rugby,
  SailboatOne,
  Sailing,
  Sandals,
  Sandwich,
  SandwichOne,
  Scallion,
  Selfie,
  SetOff,
  Shade,
  Ship,
  Shovel,
  ShovelOne,
  Shrimp,
  Skate,
  Skating,
  SkiingNordic,
  Snacks,
  Soccer,
  SoybeanMilkMaker,
  Spoon,
  Sport,
  SteeringWheel,
  Sunbath,
  Sunrise,
  Sunset,
  Sunshade,
  SwimmingPool,
  Tabletennis,
  TakeOff,
  TakeOffOne,
  Taxi,
  Tea,
  TeaDrink,
  Teapot,
  Tennis,
  Tent,
  TentBanner,
  Theater,
  ThermosCup,
  TicketsChecked,
  TicketsOne,
  TicketsTwo,
  Tomato,
  TourBus,
  Train,
  Transfer,
  Transport,
  Tray,
  Treadmill,
  Turkey,
  Universal,
  Vacation,
  VegetableBasket,
  Vegetables,
  ViciaFaba,
  Volleyball,
  VrGlasses,
  Watermelon,
  WatermelonOne,
  Weightlifting,
  Wheelchair,
  World,
} from "@icon-park/react";
import { DEFAULT_EXPENSE_ICON_KEY, DEFAULT_PARTY_ICON_KEY } from "@/domain/icons";

export { DEFAULT_EXPENSE_ICON_KEY, DEFAULT_PARTY_ICON_KEY };

/** Minimal prop surface shared by every icon-park icon component. */
export interface IconParkIconProps {
  theme?: "outline" | "filled" | "two-tone" | "multi-color";
  size?: string | number;
  /** icon-park's "multi-color" theme reads this as
   * `[outStrokeColor, outFillColor, innerStrokeColor, innerFillColor]` —
   * see `PALETTE` below. */
  fill?: string | string[];
  className?: string;
}

export type IconParkIcon = ComponentType<IconParkIconProps>;

/** The 4 slots icon-park's "multi-color" theme reads from `fill`:
 * `[outStrokeColor, outFillColor, innerStrokeColor, innerFillColor]`.
 * Not every icon's SVG art uses all 4 — a good number of icon-park's
 * catalogue (`carrot`, `croissant`, `chopsticks-fork`, `bone`, `garlic`,
 * `cocktail`, ...) is drawn as pure line art: every path is a `stroke`
 * using only `colors[0]`, with no shape ever filled from `colors[1]`. For
 * those, `colors[0]` is the *only* channel that ever reaches the screen —
 * if it's a flat neutral shared by every icon (as it was before), that
 * whole subset renders colorless no matter what the other 3 slots hold.
 * That's why each `PALETTE` tuple's first slot is a deep shade of its own
 * hue instead of one shared dark gray: it doubles as both the ink outline
 * for icons that do fill a shape and the only visible color for the ones
 * that don't. */
type IconFill = readonly [string, string, string, string];

/** Named "sticker" palettes, one per subject hue, reused across the whole
 * catalogue instead of a bespoke color pair per icon (240+ icons). Each
 * tuple is `[deep outline, main fill, inner highlight, inner fill]`. */
const PALETTE = {
  yellow: ["#8A6A00", "#FFD93B", "#FFFFFF", "#FFED9E"],
  amber: ["#8A5B00", "#F2A93B", "#FFFFFF", "#FFCF7A"],
  orange: ["#99450B", "#FF8A3D", "#FFFFFF", "#FFBC8A"],
  red: ["#992222", "#FF6B6B", "#FFFFFF", "#FFAFAF"],
  pink: ["#99295E", "#FF8FBE", "#FFFFFF", "#FFC3DD"],
  purple: ["#5A3A99", "#A987F5", "#FFFFFF", "#D6C2FB"],
  blue: ["#1B5C99", "#4FA3F7", "#FFFFFF", "#A8D2FC"],
  teal: ["#146157", "#3FC1B0", "#FFFFFF", "#9BE3D8"],
  green: ["#2E7A2E", "#6BC96B", "#FFFFFF", "#B3E3B3"],
  brown: ["#5A3820", "#B5794A", "#FFFFFF", "#D9AE83"],
  gray: ["#3F464D", "#9AA5B1", "#FFFFFF", "#D3D9DE"],
} as const satisfies Record<string, IconFill>;

export interface IconOption {
  key: string;
  label: string;
  Icon: IconParkIcon;
  fill: IconFill;
}

export const FOOD_ICONS: IconOption[] = [
  { key: "apple-one", label: "Maçã", Icon: AppleOne, fill: PALETTE.red },
  { key: "avocado", label: "Abacate", Icon: Avocado, fill: PALETTE.green },
  { key: "avocado-one", label: "Abacate", Icon: AvocadoOne, fill: PALETTE.green },
  { key: "banana", label: "Banana", Icon: Banana, fill: PALETTE.yellow },
  { key: "barbecue", label: "Churrasco", Icon: Barbecue, fill: PALETTE.orange },
  { key: "beer", label: "Cerveja", Icon: Beer, fill: PALETTE.amber },
  { key: "beer-mug", label: "Caneca de cerveja", Icon: BeerMug, fill: PALETTE.amber },
  { key: "birthday-cake", label: "Bolo de aniversário", Icon: BirthdayCake, fill: PALETTE.pink },
  { key: "bone", label: "Osso", Icon: Bone, fill: PALETTE.gray },
  { key: "bottle-one", label: "Garrafa", Icon: BottleOne, fill: PALETTE.teal },
  { key: "bottle-three", label: "Garrafa", Icon: BottleThree, fill: PALETTE.teal },
  { key: "bottle-two", label: "Garrafa", Icon: BottleTwo, fill: PALETTE.teal },
  { key: "bowl", label: "Tigela de macarrão", Icon: Bowl, fill: PALETTE.orange },
  { key: "bowl-one", label: "Tigela", Icon: BowlOne, fill: PALETTE.brown },
  { key: "bread", label: "Pão", Icon: Bread, fill: PALETTE.amber },
  { key: "bread-machine", label: "Máquina de pão", Icon: BreadMachine, fill: PALETTE.gray },
  { key: "bread-one", label: "Pão", Icon: BreadOne, fill: PALETTE.amber },
  { key: "cake", label: "Bolo", Icon: Cake, fill: PALETTE.pink },
  { key: "cake-five", label: "Bolo", Icon: CakeFive, fill: PALETTE.pink },
  { key: "cake-four", label: "Bolo", Icon: CakeFour, fill: PALETTE.pink },
  { key: "cake-one", label: "Bolo", Icon: CakeOne, fill: PALETTE.pink },
  { key: "cake-three", label: "Bolo", Icon: CakeThree, fill: PALETTE.pink },
  { key: "cake-two", label: "Bolo", Icon: CakeTwo, fill: PALETTE.pink },
  { key: "candy", label: "Doce", Icon: Candy, fill: PALETTE.pink },
  { key: "canned-fruit", label: "Fruta em lata", Icon: CannedFruit, fill: PALETTE.red },
  { key: "carrot", label: "Cenoura", Icon: Carrot, fill: PALETTE.orange },
  { key: "chafing-dish", label: "Fondue", Icon: ChafingDish, fill: PALETTE.gray },
  { key: "chafing-dish-one", label: "Fondue", Icon: ChafingDishOne, fill: PALETTE.gray },
  { key: "cheese", label: "Queijo", Icon: Cheese, fill: PALETTE.yellow },
  { key: "chef-hat-one", label: "Chapéu de chef", Icon: ChefHatOne, fill: PALETTE.gray },
  { key: "cherry", label: "Cereja", Icon: Cherry, fill: PALETTE.red },
  { key: "chicken", label: "Frango", Icon: Chicken, fill: PALETTE.brown },
  { key: "chicken-leg", label: "Coxa de frango", Icon: ChickenLeg, fill: PALETTE.brown },
  { key: "chili", label: "Pimenta", Icon: Chili, fill: PALETTE.red },
  { key: "chopping-board", label: "Tábua de corte", Icon: ChoppingBoard, fill: PALETTE.brown },
  { key: "chopsticks-fork", label: "Hashi e garfo", Icon: ChopsticksFork, fill: PALETTE.gray },
  { key: "cola", label: "Refrigerante", Icon: Cola, fill: PALETTE.brown },
  { key: "cook", label: "Cozinhar", Icon: Cook, fill: PALETTE.orange },
  { key: "cooking", label: "Cozinhando", Icon: Cooking, fill: PALETTE.orange },
  { key: "crab", label: "Caranguejo", Icon: Crab, fill: PALETTE.red },
  { key: "croissant", label: "Croissant", Icon: Croissant, fill: PALETTE.amber },
  { key: "cup-four", label: "Xícara", Icon: CupFour, fill: PALETTE.teal },
  { key: "cup-one", label: "Copo", Icon: CupOne, fill: PALETTE.teal },
  { key: "doughnut", label: "Rosquinha", Icon: Doughnut, fill: PALETTE.pink },
  { key: "drink", label: "Bebida", Icon: Drink, fill: PALETTE.teal },
  { key: "drumstick", label: "Coxinha da asa", Icon: Drumstick, fill: PALETTE.brown },
  { key: "egg", label: "Ovo frito", Icon: Egg, fill: PALETTE.yellow },
  { key: "egg-one", label: "Ovo", Icon: EggOne, fill: PALETTE.yellow },
  { key: "eggplant", label: "Berinjela", Icon: Eggplant, fill: PALETTE.purple },
  { key: "fish", label: "Peixe", Icon: Fish, fill: PALETTE.blue },
  { key: "fork-spoon", label: "Garfo e colher", Icon: ForkSpoon, fill: PALETTE.gray },
  { key: "french-fries", label: "Batata frita", Icon: FrenchFries, fill: PALETTE.yellow },
  { key: "garlic", label: "Alho", Icon: Garlic, fill: PALETTE.gray },
  { key: "glove", label: "Luva de cozinha", Icon: Glove, fill: PALETTE.red },
  { key: "goblet", label: "Taça", Icon: Goblet, fill: PALETTE.purple },
  { key: "goblet-cracking", label: "Taça quebrando", Icon: GobletCracking, fill: PALETTE.purple },
  { key: "goblet-full", label: "Taça cheia", Icon: GobletFull, fill: PALETTE.purple },
  { key: "goblet-one", label: "Taça", Icon: GobletOne, fill: PALETTE.purple },
  { key: "hamburger", label: "Hambúrguer", Icon: Hamburger, fill: PALETTE.amber },
  { key: "hamburger-one", label: "Hambúrguer", Icon: HamburgerOne, fill: PALETTE.amber },
  { key: "honey", label: "Mel", Icon: Honey, fill: PALETTE.amber },
  { key: "honey-one", label: "Mel", Icon: HoneyOne, fill: PALETTE.amber },
  { key: "hot-pot", label: "Fondue chinês", Icon: HotPot, fill: PALETTE.red },
  { key: "hot-pot-one", label: "Fondue chinês", Icon: HotPotOne, fill: PALETTE.red },
  { key: "icecream", label: "Sorvete", Icon: Icecream, fill: PALETTE.pink },
  { key: "icecream-five", label: "Picolé", Icon: IcecreamFive, fill: PALETTE.pink },
  { key: "icecream-four", label: "Sorvete", Icon: IcecreamFour, fill: PALETTE.pink },
  { key: "icecream-one", label: "Sorvete", Icon: IcecreamOne, fill: PALETTE.pink },
  { key: "icecream-three", label: "Picolé", Icon: IcecreamThree, fill: PALETTE.pink },
  { key: "icecream-two", label: "Sorvete", Icon: IcecreamTwo, fill: PALETTE.pink },
  { key: "juice", label: "Suco", Icon: Juice, fill: PALETTE.orange },
  { key: "kettle-one", label: "Chaleira", Icon: KettleOne, fill: PALETTE.gray },
  { key: "kitchen-knife", label: "Faca de cozinha", Icon: KitchenKnife, fill: PALETTE.gray },
  { key: "knife-fork", label: "Faca e garfo", Icon: KnifeFork, fill: PALETTE.gray },
  { key: "lemon", label: "Limão", Icon: Lemon, fill: PALETTE.yellow },
  { key: "liqueur", label: "Coquetel", Icon: Liqueur, fill: PALETTE.purple },
  { key: "lollipop", label: "Pirulito", Icon: Lollipop, fill: PALETTE.pink },
  { key: "macadamia-nut", label: "Castanha", Icon: MacadamiaNut, fill: PALETTE.brown },
  { key: "measuring-cup", label: "Copo medidor", Icon: MeasuringCup, fill: PALETTE.gray },
  { key: "milk", label: "Leite", Icon: Milk, fill: PALETTE.gray },
  { key: "milk-one", label: "Leite", Icon: MilkOne, fill: PALETTE.gray },
  { key: "noodles", label: "Macarrão", Icon: Noodles, fill: PALETTE.amber },
  { key: "nut", label: "Nozes", Icon: Nut, fill: PALETTE.brown },
  { key: "orange", label: "Laranja", Icon: Orange, fill: PALETTE.orange },
  { key: "orange-one", label: "Rodela de limão", Icon: OrangeOne, fill: PALETTE.yellow },
  { key: "oven", label: "Forno", Icon: Oven, fill: PALETTE.gray },
  { key: "oven-tray", label: "Assadeira", Icon: OvenTray, fill: PALETTE.gray },
  { key: "painted-eggshell", label: "Ovo decorado", Icon: PaintedEggshell, fill: PALETTE.pink },
  { key: "peach", label: "Pêssego", Icon: Peach, fill: PALETTE.pink },
  { key: "pear", label: "Pera", Icon: Pear, fill: PALETTE.green },
  { key: "peas", label: "Ervilhas", Icon: Peas, fill: PALETTE.green },
  { key: "pineapple", label: "Abacaxi", Icon: Pineapple, fill: PALETTE.yellow },
  { key: "popcorn", label: "Pipoca", Icon: Popcorn, fill: PALETTE.yellow },
  { key: "popcorn-one", label: "Pipoca", Icon: PopcornOne, fill: PALETTE.yellow },
  { key: "pot", label: "Panela", Icon: Pot, fill: PALETTE.gray },
  { key: "pumpkin", label: "Abóbora", Icon: Pumpkin, fill: PALETTE.orange },
  { key: "radish", label: "Rabanete", Icon: Radish, fill: PALETTE.red },
  { key: "radish-one", label: "Rabanete", Icon: RadishOne, fill: PALETTE.red },
  { key: "refrigerator", label: "Geladeira", Icon: Refrigerator, fill: PALETTE.blue },
  { key: "rice", label: "Arroz", Icon: Rice, fill: PALETTE.gray },
  { key: "sandwich", label: "Sanduíche", Icon: Sandwich, fill: PALETTE.amber },
  { key: "sandwich-one", label: "Sanduíche", Icon: SandwichOne, fill: PALETTE.amber },
  { key: "scallion", label: "Cebolinha", Icon: Scallion, fill: PALETTE.green },
  { key: "shovel", label: "Espátula", Icon: Shovel, fill: PALETTE.gray },
  { key: "shovel-one", label: "Espátula", Icon: ShovelOne, fill: PALETTE.gray },
  { key: "shrimp", label: "Camarão", Icon: Shrimp, fill: PALETTE.red },
  { key: "snacks", label: "Petiscos", Icon: Snacks, fill: PALETTE.orange },
  {
    key: "soybean-milk-maker",
    label: "Máquina de leite de soja",
    Icon: SoybeanMilkMaker,
    fill: PALETTE.gray,
  },
  { key: "spoon", label: "Colher", Icon: Spoon, fill: PALETTE.gray },
  { key: "tea", label: "Chá", Icon: Tea, fill: PALETTE.green },
  { key: "tea-drink", label: "Chá gelado", Icon: TeaDrink, fill: PALETTE.green },
  { key: "teapot", label: "Bule", Icon: Teapot, fill: PALETTE.green },
  { key: "thermos-cup", label: "Garrafa térmica", Icon: ThermosCup, fill: PALETTE.teal },
  { key: "tomato", label: "Tomate", Icon: Tomato, fill: PALETTE.red },
  { key: "tray", label: "Bandeja", Icon: Tray, fill: PALETTE.gray },
  { key: "turkey", label: "Peru", Icon: Turkey, fill: PALETTE.brown },
  {
    key: "vegetable-basket",
    label: "Cesta de vegetais",
    Icon: VegetableBasket,
    fill: PALETTE.green,
  },
  { key: "vegetables", label: "Vegetais", Icon: Vegetables, fill: PALETTE.green },
  { key: "vicia-faba", label: "Fava", Icon: ViciaFaba, fill: PALETTE.green },
  { key: "watermelon", label: "Melancia", Icon: Watermelon, fill: PALETTE.green },
  { key: "watermelon-one", label: "Melancia", Icon: WatermelonOne, fill: PALETTE.green },
];

export const SPORT_ICONS: IconOption[] = [
  { key: "archery", label: "Arco e flecha", Icon: Archery, fill: PALETTE.brown },
  { key: "badminton", label: "Badminton", Icon: Badminton, fill: PALETTE.teal },
  { key: "baseball", label: "Beisebol", Icon: Baseball, fill: PALETTE.blue },
  { key: "basketball", label: "Basquete", Icon: Basketball, fill: PALETTE.orange },
  { key: "bowling", label: "Boliche", Icon: Bowling, fill: PALETTE.gray },
  { key: "boxing", label: "Boxe", Icon: Boxing, fill: PALETTE.red },
  { key: "chess", label: "Xadrez", Icon: Chess, fill: PALETTE.gray },
  { key: "dumbbell", label: "Halteres", Icon: Dumbbell, fill: PALETTE.gray },
  { key: "fitness", label: "Academia", Icon: Fitness, fill: PALETTE.red },
  { key: "football", label: "Futebol americano", Icon: Football, fill: PALETTE.brown },
  { key: "gold-medal", label: "Medalha de ouro", Icon: GoldMedal, fill: PALETTE.yellow },
  { key: "golf-course", label: "Golfe", Icon: GolfCourse, fill: PALETTE.green },
  { key: "gymnastics", label: "Ginástica", Icon: Gymnastics, fill: PALETTE.purple },
  { key: "hockey", label: "Hóquei", Icon: Hockey, fill: PALETTE.blue },
  { key: "riding", label: "Equitação", Icon: Riding, fill: PALETTE.brown },
  { key: "rowing", label: "Remo", Icon: Rowing, fill: PALETTE.teal },
  { key: "rugby", label: "Rúgbi", Icon: Rugby, fill: PALETTE.brown },
  { key: "skate", label: "Skate", Icon: Skate, fill: PALETTE.purple },
  { key: "skating", label: "Patinação", Icon: Skating, fill: PALETTE.blue },
  { key: "skiing-nordic", label: "Esqui", Icon: SkiingNordic, fill: PALETTE.blue },
  { key: "soccer", label: "Futebol", Icon: Soccer, fill: PALETTE.green },
  { key: "sport", label: "Esporte", Icon: Sport, fill: PALETTE.orange },
  { key: "swimming-pool", label: "Piscina", Icon: SwimmingPool, fill: PALETTE.teal },
  { key: "tabletennis", label: "Tênis de mesa", Icon: Tabletennis, fill: PALETTE.orange },
  { key: "tennis", label: "Tênis", Icon: Tennis, fill: PALETTE.green },
  { key: "treadmill", label: "Esteira", Icon: Treadmill, fill: PALETTE.gray },
  { key: "volleyball", label: "Vôlei", Icon: Volleyball, fill: PALETTE.yellow },
  { key: "weightlifting", label: "Levantamento de peso", Icon: Weightlifting, fill: PALETTE.gray },
];

export const ACTIVITY_ICONS: IconOption[] = [
  { key: "acceleration", label: "Aceleração", Icon: Acceleration, fill: PALETTE.red },
  { key: "airplane", label: "Avião", Icon: Airplane, fill: PALETTE.blue },
  { key: "airplane-window", label: "Janela do avião", Icon: AirplaneWindow, fill: PALETTE.blue },
  {
    key: "airplane-window-one",
    label: "Janela do avião",
    Icon: AirplaneWindowOne,
    fill: PALETTE.blue,
  },
  { key: "anchor-two", label: "Âncora", Icon: AnchorTwo, fill: PALETTE.blue },
  { key: "aviation", label: "Aviação", Icon: Aviation, fill: PALETTE.blue },
  { key: "baggage-delay", label: "Bagagem atrasada", Icon: BaggageDelay, fill: PALETTE.gray },
  { key: "brake-pads", label: "Pastilha de freio", Icon: BrakePads, fill: PALETTE.gray },
  { key: "bus-one", label: "Ônibus", Icon: BusOne, fill: PALETTE.yellow },
  { key: "bus-two", label: "Ônibus", Icon: BusTwo, fill: PALETTE.yellow },
  { key: "cable-car", label: "Teleférico", Icon: CableCar, fill: PALETTE.gray },
  { key: "camp", label: "Acampamento", Icon: Camp, fill: PALETTE.green },
  { key: "car-battery", label: "Bateria do carro", Icon: CarBattery, fill: PALETTE.gray },
  { key: "check-in", label: "Check-in", Icon: CheckIn, fill: PALETTE.teal },
  { key: "cocktail", label: "Coquetel", Icon: Cocktail, fill: PALETTE.pink },
  { key: "coconut-tree", label: "Coqueiro", Icon: CoconutTree, fill: PALETTE.green },
  { key: "compass-one", label: "Bússola", Icon: CompassOne, fill: PALETTE.blue },
  { key: "consignment", label: "Despacho de bagagem", Icon: Consignment, fill: PALETTE.gray },
  { key: "cruise", label: "Cruzeiro", Icon: Cruise, fill: PALETTE.blue },
  { key: "descend", label: "Descida", Icon: Descend, fill: PALETTE.blue },
  { key: "diving", label: "Mergulho", Icon: Diving, fill: PALETTE.teal },
  { key: "earth", label: "Terra", Icon: Earth, fill: PALETTE.blue },
  { key: "enquire", label: "Inspeção de segurança", Icon: Enquire, fill: PALETTE.gray },
  { key: "fishing", label: "Pesca", Icon: Fishing, fill: PALETTE.blue },
  { key: "flag", label: "Bandeira", Icon: Flag, fill: PALETTE.red },
  { key: "flight-airflow", label: "Turbulência", Icon: FlightAirflow, fill: PALETTE.gray },
  { key: "flight-safety", label: "Segurança de voo", Icon: FlightSafety, fill: PALETTE.orange },
  { key: "frigate", label: "Fragata", Icon: Frigate, fill: PALETTE.blue },
  { key: "gate-machine", label: "Catraca de embarque", Icon: GateMachine, fill: PALETTE.gray },
  { key: "globe", label: "Globo", Icon: Globe, fill: PALETTE.blue },
  { key: "gps", label: "GPS", Icon: Gps, fill: PALETTE.red },
  { key: "guide-board", label: "Placa de sinalização", Icon: GuideBoard, fill: PALETTE.yellow },
  { key: "high-speed-rail", label: "Trem-bala", Icon: HighSpeedRail, fill: PALETTE.blue },
  { key: "homestay", label: "Pousada", Icon: Homestay, fill: PALETTE.orange },
  { key: "hot-air-balloon", label: "Balão de ar quente", Icon: HotAirBalloon, fill: PALETTE.red },
  { key: "in-flight", label: "Em voo", Icon: InFlight, fill: PALETTE.blue },
  { key: "international", label: "Internacional", Icon: International, fill: PALETTE.blue },
  { key: "journey", label: "Viagem", Icon: Journey, fill: PALETTE.teal },
  { key: "landing", label: "Pouso", Icon: Landing, fill: PALETTE.blue },
  { key: "landscape", label: "Paisagem", Icon: Landscape, fill: PALETTE.green },
  { key: "local", label: "Localização confirmada", Icon: Local, fill: PALETTE.red },
  { key: "local-pin", label: "Local", Icon: LocalPin, fill: PALETTE.red },
  { key: "local-two", label: "Local", Icon: LocalTwo, fill: PALETTE.red },
  { key: "luggage", label: "Mala", Icon: Luggage, fill: PALETTE.brown },
  { key: "manual-gear", label: "Câmbio manual", Icon: ManualGear, fill: PALETTE.gray },
  { key: "map-distance", label: "Distância no mapa", Icon: MapDistance, fill: PALETTE.teal },
  { key: "map-draw", label: "Traçar rota", Icon: MapDraw, fill: PALETTE.teal },
  { key: "map-road", label: "Mapa e rota", Icon: MapRoad, fill: PALETTE.teal },
  { key: "map-road-two", label: "Mapa e rota", Icon: MapRoadTwo, fill: PALETTE.teal },
  { key: "map-two", label: "Mapa", Icon: MapTwo, fill: PALETTE.teal },
  { key: "mark", label: "Marcador", Icon: Mark, fill: PALETTE.red },
  { key: "mountain", label: "Montanha", Icon: Mountain, fill: PALETTE.green },
  { key: "mounted", label: "Passeio a cavalo", Icon: Mounted, fill: PALETTE.brown },
  { key: "navigation", label: "Navegação", Icon: Navigation, fill: PALETTE.blue },
  { key: "parachute", label: "Paraquedas", Icon: Parachute, fill: PALETTE.red },
  { key: "parking", label: "Estacionamento", Icon: Parking, fill: PALETTE.blue },
  { key: "passport-one", label: "Passaporte", Icon: PassportOne, fill: PALETTE.blue },
  { key: "pennant", label: "Bandeirola", Icon: Pennant, fill: PALETTE.red },
  { key: "photograph", label: "Foto de viagem", Icon: Photograph, fill: PALETTE.purple },
  { key: "planet", label: "Planeta", Icon: Planet, fill: PALETTE.purple },
  { key: "pyramid-one", label: "Pirâmide", Icon: PyramidOne, fill: PALETTE.yellow },
  { key: "railway", label: "Ferrovia", Icon: Railway, fill: PALETTE.gray },
  { key: "repositioning", label: "Reposicionar", Icon: Repositioning, fill: PALETTE.blue },
  { key: "resting", label: "Descanso", Icon: Resting, fill: PALETTE.teal },
  { key: "riding-one", label: "Passeio a cavalo", Icon: RidingOne, fill: PALETTE.brown },
  { key: "road", label: "Estrada", Icon: Road, fill: PALETTE.gray },
  { key: "road-cone", label: "Cone de trânsito", Icon: RoadCone, fill: PALETTE.orange },
  { key: "road-one", label: "Estrada", Icon: RoadOne, fill: PALETTE.gray },
  { key: "road-sign", label: "Placa de trânsito", Icon: RoadSign, fill: PALETTE.yellow },
  { key: "road-sign-both", label: "Placa de trânsito", Icon: RoadSignBoth, fill: PALETTE.yellow },
  { key: "rocket", label: "Foguete", Icon: Rocket, fill: PALETTE.red },
  { key: "round-trip", label: "Ida e volta", Icon: RoundTrip, fill: PALETTE.blue },
  { key: "sailboat-one", label: "Veleiro", Icon: SailboatOne, fill: PALETTE.blue },
  { key: "sailing", label: "Navegação a vela", Icon: Sailing, fill: PALETTE.blue },
  { key: "sandals", label: "Sandálias", Icon: Sandals, fill: PALETTE.orange },
  { key: "selfie", label: "Selfie", Icon: Selfie, fill: PALETTE.pink },
  { key: "set-off", label: "Partida", Icon: SetOff, fill: PALETTE.blue },
  { key: "shade", label: "Sombra", Icon: Shade, fill: PALETTE.gray },
  { key: "ship", label: "Navio", Icon: Ship, fill: PALETTE.blue },
  { key: "steering-wheel", label: "Volante", Icon: SteeringWheel, fill: PALETTE.gray },
  { key: "sunbath", label: "Banho de sol", Icon: Sunbath, fill: PALETTE.yellow },
  { key: "sunrise", label: "Nascer do sol", Icon: Sunrise, fill: PALETTE.orange },
  { key: "sunset", label: "Pôr do sol", Icon: Sunset, fill: PALETTE.orange },
  { key: "sunshade", label: "Guarda-sol", Icon: Sunshade, fill: PALETTE.teal },
  { key: "take-off", label: "Decolagem", Icon: TakeOff, fill: PALETTE.blue },
  { key: "take-off-one", label: "Decolagem", Icon: TakeOffOne, fill: PALETTE.blue },
  { key: "taxi", label: "Táxi", Icon: Taxi, fill: PALETTE.yellow },
  { key: "tent", label: "Barraca", Icon: Tent, fill: PALETTE.green },
  { key: "tent-banner", label: "Barraca com bandeira", Icon: TentBanner, fill: PALETTE.green },
  { key: "theater", label: "Cinema", Icon: Theater, fill: PALETTE.purple },
  {
    key: "tickets-checked",
    label: "Ingresso validado",
    Icon: TicketsChecked,
    fill: PALETTE.purple,
  },
  { key: "tickets-one", label: "Ingresso", Icon: TicketsOne, fill: PALETTE.purple },
  { key: "tickets-two", label: "Ingresso", Icon: TicketsTwo, fill: PALETTE.purple },
  { key: "tour-bus", label: "Ônibus de turismo", Icon: TourBus, fill: PALETTE.yellow },
  { key: "train", label: "Trem", Icon: Train, fill: PALETTE.blue },
  { key: "transfer", label: "Conexão de voo", Icon: Transfer, fill: PALETTE.blue },
  { key: "transport", label: "Transporte", Icon: Transport, fill: PALETTE.blue },
  { key: "universal", label: "Universo", Icon: Universal, fill: PALETTE.purple },
  { key: "vacation", label: "Férias", Icon: Vacation, fill: PALETTE.teal },
  { key: "wheelchair", label: "Cadeira de rodas", Icon: Wheelchair, fill: PALETTE.blue },
  { key: "world", label: "Mundo", Icon: World, fill: PALETTE.blue },
  { key: "movie", label: "Filme", Icon: Movie, fill: PALETTE.purple },
  { key: "movie-board", label: "Claquete de cinema", Icon: MovieBoard, fill: PALETTE.gray },
  { key: "music", label: "Música", Icon: Music, fill: PALETTE.pink },
  { key: "microphone", label: "Show ao vivo", Icon: Microphone, fill: PALETTE.pink },
  { key: "party-balloon", label: "Balão de festa", Icon: PartyBalloon, fill: PALETTE.pink },
  { key: "fireworks", label: "Fogos de artifício", Icon: Fireworks, fill: PALETTE.purple },
  { key: "ferris-wheel", label: "Roda-gigante", Icon: FerrisWheel, fill: PALETTE.pink },
  { key: "circus", label: "Circo", Icon: Circus, fill: PALETTE.red },
  { key: "museum-one", label: "Museu", Icon: MuseumOne, fill: PALETTE.yellow },
  { key: "hotel", label: "Hotel", Icon: Hotel, fill: PALETTE.blue },
  { key: "beach-umbrella", label: "Guarda-sol de praia", Icon: BeachUmbrella, fill: PALETTE.teal },
  { key: "game", label: "Jogo", Icon: Game, fill: PALETTE.purple },
  { key: "game-console", label: "Videogame", Icon: GameConsole, fill: PALETTE.purple },
  { key: "gamepad", label: "Controle de videogame", Icon: Gamepad, fill: PALETTE.purple },
  { key: "vr-glasses", label: "Óculos de VR", Icon: VrGlasses, fill: PALETTE.purple },
];

export interface IconCategory {
  label: string;
  icons: IconOption[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  { label: "Comida & Bebida", icons: FOOD_ICONS },
  { label: "Esporte", icons: SPORT_ICONS },
  { label: "Atividades", icons: ACTIVITY_ICONS },
];

const ICON_MAP = new Map<string, IconOption>(
  ICON_CATEGORIES.flatMap((category) => category.icons).map((icon) => [icon.key, icon]),
);

/**
 * Resolves a stored `emoji` string to its full catalogue entry (component +
 * color palette). Unknown values (e.g. a raw emoji left over from before
 * this feature) fall back to the default expense icon instead of rendering
 * as text.
 */
function resolveIconOption(key: string): IconOption {
  return ICON_MAP.get(key) ?? ICON_MAP.get(DEFAULT_EXPENSE_ICON_KEY)!;
}

/**
 * Renders a stored `emoji` key as its icon-park component with the
 * "multi-color" theme and that icon's own `PALETTE` fill — the single
 * place this pairing happens, so every call site automatically gets
 * per-icon colors instead of icon-park's flat default palette.
 */
export function AppIcon({
  iconKey,
  size,
  className,
}: {
  iconKey: string;
  size?: string | number;
  className?: string;
}) {
  const { Icon, fill } = resolveIconOption(iconKey);
  return <Icon theme="multi-color" size={size} fill={[...fill]} className={className} />;
}
